# Generated by Django 6.0.3 on 2026-03-28 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_password_session_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['group', 'codename'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('courier', 'Courier'), ('manager', 'Manager'), ('admin', 'Admin')], db_index=True, max_length=20)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='base.permission')),
            ],
            options={
                'db_table': 'role_permissions',
                'indexes': [models.Index(fields=['role'], name='idx_role_perm_role')],
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='uq_role_permission')],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_granted', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='base.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='base.user')),
            ],
            options={
                'db_table': 'user_permissions',
                'indexes': [models.Index(fields=['user_id'], name='idx_user_perm_user')],
                'constraints': [models.UniqueConstraint(fields=('user', 'permission'), name='uq_user_permission')],
            },
        ),
    ]
