# Generated by Django 6.0.3 on 2026-04-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_permission_rolepermission_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'sort_order'], name='idx_products_featured_sort'),
        ),
    ]
