# Generated by Django 6.0.3 on 2026-04-03 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_add_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='base.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivering_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preparing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_courier_id', 'status'], name='idx_orders_courier_status'),
        ),
    ]
