# Generated by Django 6.0.3 on 2026-04-06 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='EAN-13, UPC, or internal barcode', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase/cost price for margin tracking', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Alert when stock_qty falls below this', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock keeping unit, e.g. "FRU-APL-001"', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='idx_products_sku'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='idx_products_barcode'),
        ),
    ]
