# Generated by Django 6.0.4 on 2026-04-27 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_add_user_phone_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.IntegerField(choices=[(0, 'Sale'), (1, 'Refund')], default=0)),
                ('receipt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to OFD'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_amount', models.BigIntegerField(help_text='Total including VAT, in tiyin')),
                ('total_vat', models.BigIntegerField(default=0, help_text='Total VAT, in tiyin')),
                ('received_cash', models.BigIntegerField(default=0)),
                ('received_card', models.BigIntegerField(default=0)),
                ('fiscal_sign', models.CharField(blank=True, default='', max_length=255)),
                ('ofd_receipt_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('qr_code_url', models.CharField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('transaction_time', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fiscal_receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiscalReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('mxik_code', models.CharField(max_length=17)),
                ('barcode', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_code', models.CharField(blank=True, default='', max_length=10)),
                ('unit_price', models.BigIntegerField(help_text='In tiyin')),
                ('discount', models.BigIntegerField(default=0)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('vat_amount', models.BigIntegerField(default=0, help_text='In tiyin')),
                ('total_amount', models.BigIntegerField(help_text='In tiyin, after discount, with VAT')),
            ],
            options={
                'db_table': 'fiscal_receipt_items',
            },
        ),
        migrations.CreateModel(
            name='MxikCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=17, unique=True)),
                ('name_uz', models.CharField(max_length=500)),
                ('name_ru', models.CharField(blank=True, default='', max_length=500)),
                ('class_code', models.CharField(blank=True, default='', max_length=5)),
                ('class_name', models.CharField(blank=True, default='', max_length=255)),
                ('group_name', models.CharField(blank=True, default='', max_length=255)),
                ('unit_code', models.CharField(blank=True, default='', help_text='e.g. 796=piece, 166=kg', max_length=10)),
                ('unit_name', models.CharField(blank=True, default='', max_length=50)),
                ('package_code', models.CharField(blank=True, default='', max_length=20)),
                ('package_name', models.CharField(blank=True, default='', max_length=255)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mxik_codes',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='total_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mxik_code',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='mxik_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='MXIK product classification code from tasnif.soliq.uz', max_length=17),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=12, help_text='VAT rate percent (12% standard, 0% for some food items)', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['mxik_code'], name='idx_products_mxik'),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_receipts', to='base.order'),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='refund_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='base.fiscalreceipt'),
        ),
        migrations.AddField(
            model_name='fiscalreceiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.fiscalreceipt'),
        ),
        migrations.AddIndex(
            model_name='mxikcode',
            index=models.Index(fields=['class_code'], name='idx_mxik_class'),
        ),
        migrations.AddIndex(
            model_name='mxikcode',
            index=models.Index(fields=['name_uz'], name='idx_mxik_name'),
        ),
        migrations.AddIndex(
            model_name='fiscalreceipt',
            index=models.Index(fields=['status'], name='idx_fiscal_status'),
        ),
        migrations.AddIndex(
            model_name='fiscalreceipt',
            index=models.Index(fields=['order_id'], name='idx_fiscal_order'),
        ),
        migrations.AddIndex(
            model_name='fiscalreceipt',
            index=models.Index(fields=['transaction_time'], name='idx_fiscal_txn_time'),
        ),
        migrations.AddIndex(
            model_name='fiscalreceiptitem',
            index=models.Index(fields=['receipt_id'], name='idx_fiscal_item_receipt'),
        ),
    ]
