# Generated by Django 6.0.3 on 2026-04-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_add_fiscal_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fiscalreceipt',
            name='idx_fiscal_status',
        ),
        migrations.RemoveIndex(
            model_name='fiscalreceipt',
            name='idx_fiscal_order',
        ),
        migrations.RemoveIndex(
            model_name='fiscalreceipt',
            name='idx_fiscal_txn_time',
        ),
        migrations.RemoveIndex(
            model_name='fiscalreceiptitem',
            name='idx_fiscal_item_receipt',
        ),
        migrations.RemoveIndex(
            model_name='mxikcode',
            name='idx_mxik_class',
        ),
        migrations.RemoveIndex(
            model_name='mxikcode',
            name='idx_mxik_name',
        ),
        migrations.DeleteModel(
            name='MxikCode',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='idx_payments_external',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_products_mxik',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='mxik_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vat_rate',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='fiscalreceiptitem',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider_data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mxik_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vat_rate',
        ),
        migrations.DeleteModel(
            name='FiscalReceipt',
        ),
        migrations.DeleteModel(
            name='FiscalReceiptItem',
        ),
    ]
