# Generated by Django 6.0.3 on 2026-05-01 06:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_fiscal_and_simplify_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('coupon', 'Coupon'), ('free_delivery', 'Free Delivery'), ('bonus_product', 'Bonus Product')], max_length=30)),
                ('is_active', models.BooleanField(default=False, help_text='Only one reward active at a time')),
                ('coupon_type', models.CharField(blank=True, default='percent', help_text='percent or fixed', max_length=20)),
                ('coupon_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('coupon_max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percent type', max_digits=12, null=True)),
                ('coupon_min_order', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order to use coupon', max_digits=12, null=True)),
                ('coupon_expires_days', models.IntegerField(default=30, help_text='0 = no expiry')),
                ('free_delivery_count', models.IntegerField(default=1, help_text='Number of free delivery orders')),
                ('bonus_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=8)),
                ('bonus_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.product')),
            ],
            options={
                'db_table': 'referral_rewards',
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('coupon', 'Coupon'), ('free_delivery', 'Free Delivery'), ('bonus_product', 'Bonus Product')], max_length=30)),
                ('free_deliveries_remaining', models.IntegerField(default=0)),
                ('bonus_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('bonus_claimed', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bonus_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.product')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.coupon')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='base.referral')),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_rewards', to='base.referralreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='base.user')),
            ],
            options={
                'db_table': 'user_rewards',
            },
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['is_active'], name='idx_ref_rewards_active'),
        ),
        migrations.AddIndex(
            model_name='userreward',
            index=models.Index(fields=['user_id', 'is_used'], name='idx_user_rewards_active'),
        ),
        migrations.AddIndex(
            model_name='userreward',
            index=models.Index(fields=['user_id', 'type'], name='idx_user_rewards_type'),
        ),
    ]
